#!/bin/bash

cd "$(dirname "$0")"

cd ../src/js
../../min/assets/jscompress ../../min/initial-js.min.js app.js controllers/masterCtrl.js controllers/categoryCtrl.js controllers/gameCtrl.js directives/para-back.js services/httpx.js

# The code to compress all the lazy-loaded JS:
#../../min/assets/jscompress ../../min/lazy-js.min.js directives/scroll.js controllers/lazyStuff.js controllers/cookieCtrl.js controllers/mailListCtrl.js controllers/submitCtrl.js controllers/homeCtrl.js services/local-storage.js filters/mouth-wash.js filters/chat-time.js directives/embed-src.js controllers/404Ctrl.js

# Code to compress all lazy-loaded JS except mailListCtrl (because the mail system is not ready yet)
../../min/assets/jscompress ../../min/lazy-js.min.js directives/scroll.js controllers/lazyStuff.js controllers/cookieCtrl.js controllers/submitCtrl.js controllers/homeCtrl.js filters/mouth-wash.js filters/chat-time.js directives/embed-src.js controllers/404Ctrl.js

cd ..
minify -o ../min/main.min.css css/main.css
