#!/bin/sh
cd "$(dirname "$0")"
git pull
OLD_FILE=`cat initialJSON.json`
curl -L https://script.google.com/macros/s/AKfycbzEVUBnYRqGOFS6309I9Oe748omXUWLjpDScrjYatNvxKuL6BEU/exec > /tmp/initialJSON.json
NEW_FILE=`cat /tmp/initialJSON.json`
if [ "$NEW_FILE" != "$OLD_FILE" ]; then
  echo "Changes have been made to initialJSON.json => pushing changes…"
  cp /tmp/initialJSON.json .
  git add .
  git commit --amend --no-edit
  git push -f
else
  echo "No changes => not doing anything"
fi

OLD_SITEMAP=`cat sitemap.xml`
NEW_SITEMAP=`curl -L https://script.google.com/macros/s/AKfycbxPwMbWpjuGXhg5btsB2-bWxLX7owBWZInnlIdmItbNDRWtiPU/exec`
if [ "$OLD_SITEMAP" != "$NEW_SITEMAP" ]; then
  echo "Changes have been made to the sitemap => pushing changes…"
  echo $NEW_SITEMAP > sitemap.xml
  git add .
  git commit --amend --no-edit
  git push -f
else
  echo "No changes to sitemap => not doing anything"
fi
