app.filter('mouthWash', function() {

  var badWords = [
    "fuck ",
    " fuck",
    "sex ",
    " sex",
    " porn",
    "porn ",
    " faen ",
    " fakk ",
    " føkk ",
    " knull ",
    " pul ",
    " wank ",
    " runk ",
    " satan ",
    " bitch ",
    " fitte ",
    " fitta ",
    " jævl",
    " jævel ",
    " mens",
    "kill y",
    " necro",
    "rape ",
    "anus ",
    "arse ",
    " ass ",
    " axwound ",
    "blow job",
    "blowjob",
    " bollock ",
    " bollox ",
    " boner ",
    " butt ",
    "camel toe",
    " chode ",
    " clit ",
    "cock ",
    " cooch ",
    " cum ",
    " cunt ",
    " dick ",
    " dildo ",
    " fag",
    " gay ",
    " homo ",
    " handjob ",
    " jerk ",
    " jack",
    " lesbi ",
    " phil ",
    "fil ",
    " nigg ",
    " paki ",
    " penis ",
    " pecker ",
    " piss ",
    " poon ",
    " prick ",
    " pussy ",
    " shit",
    "slut ",
    " suck ",
    " twat ",
    " tit",
    "tard ",
    "tards ",
    " vagin",
    " whore ",
    " 4r5e ",
    " 5h1t ",
    " 5hit ",
    " a55 ",
    " anal ",
    " ar5e ",
    " arrse ",
    " ass-fucker ",
    " asses ",
    " assfucker ",
    " assfukka ",
    " asshole ",
    " assholes ",
    " asswhole ",
    " a_s_s ",
    " b!tch ",
    " b00bs ",
    " b17ch ",
    " b1tch ",
    " ballbag ",
    " balls ",
    " ballsack ",
    " bastard ",
    " beastial ",
    " beastiality ",
    " bellend ",
    " bestial ",
    " bestiality ",
    " bich ",
    " biatch ",
    " bitcher ",
    " bitchers ",
    " bitches ",
    " bitchin ",
    " bitching ",
    " bloody ",
    " blowjobs ",
    " boiolas ",
    " bollok ",
    " boob ",
    " boobs ",
    " booobs ",
    " boooobs ",
    " booooobs ",
    " booooooobs ",
    " breasts ",
    " buceta ",
    " bugger ",
    " bum ",
    "bunny fucker",
    " butthole ",
    " buttmuch ",
    " buttplug ",
    " c0ck ",
    " c0cksucker ",
    "carpet muncher",
    " cawk ",
    " chink ",
    " cipa ",
    " cl1t ",
    " clitoris ",
    " clits ",
    " cnut ",
    " cok ",
    "cokmuncher",
    "coksucka",
    " coon ",
    " cox ",
    " crap ",
    " cummer ",
    " cumming ",
    " cums ",
    " cumshot ",
    "cunilingus",
    "cunillingus",
    "cunnilingus",
    "cuntlick",
    "cunts ",
    " cyalis ",
    " cyberfuc",
    "d1ck",
    " damn ",
    "dickhead",
    " dildos ",
    " dink ",
    " dinks ",
    " dirsa ",
    " dlck ",
    "dog-fucker",
    " doggin ",
    " dogging ",
    "donkeyribber",
    " doosh ",
    " duche ",
    " dyke ",
    " ejaculat",
    " ejakulat",
    "f u c k",
    "f4nny",
    " fag ",
    " fagging ",
    " faggitt ",
    " faggot ",
    " faggs ",
    " fagot ",
    " fagots ",
    " fags ",
    " fanny ",
    " fannyflaps ",
    " fannyfucker ",
    " fanyy ",
    " fatass ",
    " fcuk ",
    " fcuker ",
    " fcuking ",
    " feck ",
    " fecker ",
    " felching ",
    " fellate ",
    " fellatio ",
    "fingerfuck",
    "fistfuck",
    " flange ",
    " fook ",
    " fooker ",
    " fuck",
    " fuk",
    " fux ",
    "fux0r",
    "f_u_c_k",
    "gangbang",
    " gay",
    " goatse ",
    " hell ",
    " heshe ",
    " hoar ",
    " hoare ",
    " hoer ",
    " hore ",
    " horniest ",
    " horny",
    "jackoff",
    " jap ",
    "jerk-off ",
    " jism ",
    "jiz ",
    "jizm ",
    " jizz ",
    " kawk ",
    " knob ",
    " knobead ",
    " knobed ",
    " knobend ",
    " knobhead ",
    " knobjocky ",
    " knobjokey ",
    " kock ",
    " kondum ",
    " kondums ",
    " kum ",
    " kummer ",
    " kumming ",
    " kums ",
    " kunilingus ",
    " l3ich ",
    " l3itch ",
    " labia ",
    " lust ",
    " lusting ",
    " m0f0 ",
    " m0fo ",
    " m45terbate ",
    " ma5terb8 ",
    " ma5terbate ",
    " masochist ",
    " master-bate ",
    " masterb8 ",
    " masterbat",
    " masturbat",
    "mo-fo",
    " mof0 ",
    " mofo ",
    " mothafuck",
    "mother fucker",
    " motherfuck",
    " muff ",
    " mutha ",
    " muthafecker ",
    " muthafuckker ",
    " muther ",
    " mutherfucker ",
    " n1gg",
    " nazi",
    " nigg",
    " nob jokey",
    " nobhead",
    " nobjocky",
    " nobjokey",
    "numbnuts",
    "nutsack",
    " orgasim",
    " orgasm",
    "p0rn",
    " fucker",
    " phuck ",
    " phuk",
    " phuq ",
    "fucker ",
    "pimpis",
    " piss",
    "pricks ",
    " pron ",
    " pube ",
    " pusse",
    " pussi",
    "pussys ",
    "rectum ",
    " retard",
    " rimjaw",
    "rimming ",
    " schlong ",
    "screwing ",
    " scroat ",
    " scrot",
    " semen",
    "sh!",
    "sh1t",
    " shag",
    "shag ",
    "shagger ",
    "shaggin",
    "shemale",
    " shit",
    "shit ",
    " skank",
    "skank ",
    "sluts ",
    " smegma ",
    " smut ",
    "son-of-a-bitch",
    " spac ",
    " spunk ",
    " s_h_i_t ",
    "t1tt1e5",
    "t1tties",
    " teets ",
    " teez ",
    " testic",
    " tit",
    "tit ",
    " tosser ",
    "tw4t",
    " twat",
    "twat ",
    "v14gra",
    "v1gra",
    " vagin",
    " viagra ",
    "vulva ",
    " vulva",
    " wang ",
    " wank",
    "whoar ",
    "xrated",
    " xxx ",
    "fy fader"
  ];

  return function(input, scope) {
    if (!scope.master.verifiedUser && typeof input !== "undefined") {
      angular.forEach(badWords, function(word){
        let regex = new RegExp(word.split('').join('\\s*'), 'gi');
        input = input.replace(regex, " mooh ");
      });
    }
    return input;
  };

});
